from __future__ import annotations

from torch_weighttracker.calculations.base import CalcType, Calculation
from torch_weighttracker.calculations.calcs import (
    ActiveMacsPrModuleCalc,
    BaselineMacsPrModuleCalc,
    BaselineModuleAxesCalc,
    BaselineParamPrUnitPrGroup,
    Block24SparsityCalc,
    InitialUnitCountPrGroup,
    L2NormPrUnit,
    ModuleAxisCostIndicesCalc,
    ParamPrUnit,
    UnitActiveMaskCalc,
    UnitPrGroup,
    UnitsToGroup,
    UnstructuredSparsityPrModuleCalc,
    create_active_macs_pr_module_calc,
    create_active_units_calc,
    create_baseline_group_sizes_calc,
    create_baseline_macs_pr_module_calc,
    create_baseline_module_axes_calc,
    create_baseline_param_pr_unit_pr_group_calc,
    create_bitrate_pr_module_calc,
    create_block_2_4_sparsity_calc,
    create_group_change_effect_calc,
    create_group_sizes_calc,
    create_group_unit_param_change_calc,
    create_groups_to_units_calc,
    create_l2_norm_pr_unit_calc,
    create_module_axis_cost_indices_calc,
    create_param_pr_unit_calc,
    create_structured_unit_sum_calc,
    create_unit_active_mask_calc,
    create_unit_delta_to_module_axis_calc,
    create_units_to_group_calc,
    create_units_to_module_axis_calc,
    create_unstructured_sparsity_pr_module_calc,
)
from torch_weighttracker.calculations.context import CalculationContext
from torch_weighttracker.calculations.pipeline_calc import PipelineCalc
from torch_weighttracker.calculations.reduction_calc import ReductionCalc
from torch_weighttracker.calculations.registry import CALCULATION_SPECS
from torch_weighttracker.calculations.spec import CalculationSpec

__all__ = [
    "ActiveMacsPrModuleCalc",
    "BaselineMacsPrModuleCalc",
    "BaselineModuleAxesCalc",
    "BaselineParamPrUnitPrGroup",
    "Block24SparsityCalc",
    "CALCULATION_SPECS",
    "CalcType",
    "Calculation",
    "CalculationContext",
    "CalculationSpec",
    "InitialUnitCountPrGroup",
    "L2NormPrUnit",
    "ModuleAxisCostIndicesCalc",
    "ParamPrUnit",
    "PipelineCalc",
    "ReductionCalc",
    "UnitActiveMaskCalc",
    "UnitPrGroup",
    "UnitsToGroup",
    "UnstructuredSparsityPrModuleCalc",
    "create_active_macs_pr_module_calc",
    "create_active_units_calc",
    "create_baseline_group_sizes_calc",
    "create_baseline_macs_pr_module_calc",
    "create_baseline_module_axes_calc",
    "create_baseline_param_pr_unit_pr_group_calc",
    "create_bitrate_pr_module_calc",
    "create_block_2_4_sparsity_calc",
    "create_group_change_effect_calc",
    "create_group_unit_param_change_calc",
    "create_group_sizes_calc",
    "create_groups_to_units_calc",
    "create_l2_norm_pr_unit_calc",
    "create_module_axis_cost_indices_calc",
    "create_param_pr_unit_calc",
    "create_structured_unit_sum_calc",
    "create_unit_active_mask_calc",
    "create_unit_delta_to_module_axis_calc",
    "create_unstructured_sparsity_pr_module_calc",
    "create_units_to_group_calc",
    "create_units_to_module_axis_calc",
]
